server:
  host: 127.0.0.1
  port: 12379
# tls:
#   cert: /path/to/file.pem
#   key: /path/to/file.pem

datasource:
  type: mysql
  mysql:
    host: 172.20.4.4
    port: 3306
    username: root
    password:
    database: apisix
