name: E2E test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0
        ports:
          - 3306:3306
        env:
          ALLOW_EMPTY_PASSWORD: yes
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v3
        with:
          go-version: "1.17"

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Build ETCD Adapter
        run: go build -o ./test/e2e/etcd-adapter main.go

      - name: Run test cases
        working-directory: ./test/e2e
        run: |
          go mod download
          ginkgo -r

      - name: Run tmate debugger
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
