name: E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0
        ports:
          - 3306:3306
        env:
          ALLOW_EMPTY_PASSWORD: yes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Ginkgo
        run: |
          GINKGO_VERSION=$(cd test/e2e && go list -m  -mod=readonly  -f {{.Version}}  github.com/onsi/ginkgo/v2)
          go install github.com/onsi/ginkgo/v2/ginkgo@$GINKGO_VERSION
          sudo cp ~/go/bin/ginkgo /usr/local/bin

      - name: Run test cases
        run: make e2e-test
